# Generated by Django 5.1.4 on 2024-12-19 01:35

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PythonModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', tinymce.models.HTMLField()),
                ('published', models.BooleanField()),
                ('display_order', models.IntegerField(blank=True, null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
    ]
